### PR TITLE
191220080-Hw01

### PR DESCRIPTION
**Pull request by PandaAwAke**

### CODE REVIEW

**Review by caochun — CHANGES_REQUESTED** [review]
do not change files of other people

**Comment by PandaAwAke** [comment]
Sry, I even did not open any other's file, I just deleted others' files.
Now I've updated my forked repository to the newest version.
Thanks!

**Comment by PandaAwAke** [comment]
Hello! And I've already updated my repository again and renamed my folder to 'S191220080'.

**Review by caochun — CHANGES_REQUESTED** [review]
pls do not change .gitignore

**Comment by PandaAwAke** [comment]
OK, I think it's done now, sry for this ToT

**Pull request merged**
