### PR TITLE
191220158

### PR DESCRIPTION
**Pull request by Da-Gen-Dui-Zhang-Lai-La**

### CODE REVIEW

**Review by caochun — CHANGES_REQUESTED** [review]
https://www.jianshu.com/p/f42a1894f6e9

pls read the code convention

**Comment by Da-Gen-Dui-Zhang-Lai-La** [comment]
> https://www.jianshu.com/p/f42a1894f6e9
> 
> pls read the code convention

Thanks, teacher. Should I rewrite my code and resubmit it?

**Comment by caochun** [comment]
yes, pls

**Review by caochun — CHANGES_REQUESTED** [review]
pls resolve the conflicts

**Comment by Da-Gen-Dui-Zhang-Lai-La** [comment]
> pls resolve the conflicts

sry teacher,I don't know how to modify it here,I changer my code and pull request again yesterday and passed it， my student number is 191220158， you may find my number in main

**Pull request closed without merging**
